#define BLOCK_WIDTH 16

//#define WRITE_RANDOM_SPRAYS_TO_DISK
//#define ENABLE_STRESS_G2G_CPU_1
//#define ENABLE_STRESS_G2G_CPU_2
//#define ENABLE_STRESS_G2G_CPU_3
//#define ENABLE_STRESS_C2G_CPU_3
//#define ENABLE_STRESS_C2C_CPU_3
//#define ENABLE_STRESS_C2G_GPU_1
#define ENABLE_STRESS_C2G_GPU_2
//#define ENABLE_STRESS_C2G_GPU_3